# Generated by Django 4.0.3 on 2022-03-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.ImageField(default=0, upload_to='')),
                ('description', models.CharField(default=' ', max_length=350)),
                ('image', models.ImageField(upload_to='products/')),
            ],
        ),
    ]
